# Generated by Django 2.1.2 on 2019-01-02 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('create_time', models.DateField(auto_created=True, auto_now=True, verbose_name='创建时间')),
                ('nickname', models.CharField(default='', max_length=255, null=True, verbose_name='用户名')),
                ('user_id', models.CharField(default='', max_length=10, primary_key=True, serialize=False, verbose_name='用户id')),
                ('password', models.CharField(default='123456', max_length=16, verbose_name='密码')),
                ('status', models.IntegerField(default=0, null=True, verbose_name='甲乙区分')),
                ('desc', models.CharField(default='', max_length=255, null=True, verbose_name='负责项目')),
                ('last_login', models.DateField(verbose_name='最后登录时间')),
                ('avatar', models.ImageField(blank=True, default='image/default.png', null=True, upload_to='avatar/%Y/%m', verbose_name='头像')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('partment_code', models.CharField(default='000000', max_length=10, primary_key=True, serialize=False, verbose_name='部门ID')),
                ('partment_desc', models.CharField(default='', max_length=255, verbose_name='部门名称')),
                ('partment_lev', models.IntegerField(default=0, verbose_name='部门级别')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.Department', verbose_name='部门'),
        ),
    ]
