# Generated by Django 2.1.2 on 2019-01-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_file',
            field=models.FileField(null=True, upload_to='ticket/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='ticketconfim',
            name='confirm_file',
            field=models.FileField(null=True, upload_to='handle/%Y/%m/%d'),
        ),
    ]
